### ISSUE TITLE
Ventrilo Server Stats - error displayed

### ISSUE THREAD

**Issue by DNA-styx** [DNA-styx/HLSTATSX-Windmill-Theme#8]
`Fatal error
: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/stats.dnagames.site/pages/ventrilostatus.php:320 Stack trace: #0 /var/www/stats.dnagames.site/pages/ventrilo.php(28): CVentriloStatus->ChannelFind() #1 /var/www/stats.dnagames.site/pages/ventrilo.php(188): VentriloDisplayEX1() #2 /var/www/stats.dnagames.site/hlstats.php(228): include('...') #3 {main} thrown in
/var/www/stats.dnagames.site/pages/ventrilostatus.php
on line
320`

**Comment by DNA-styx** [comment]
Vent server usage is so low it's not worth fixing this ( unless I hear otherwise)
